---
# tasks file for os_kernel

- name: Ensure Kernel Hardening via Sysctl is present
  become: yes
  copy:
    dest: "/etc/sysctl.d/10-harden_sysctl.conf"
    content: |
      ## Kernel Items
      fs.suid_dumpable = 0
      kernel.randomize_va_space = 2

      ## IPV4 Networking
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv4.conf.all.accept_source_route = 0
      net.ipv4.conf.all.log_martians = 0
      net.ipv4.conf.all.rp_filter = 0
      net.ipv4.conf.all.secure_redirects = 0
      net.ipv4.conf.all.send_redirects = 0
      net.ipv4.conf.default.accept_redirects = 0
      net.ipv4.conf.default.accept_source_route = 0
      net.ipv4.conf.default.log_martians = 0
      net.ipv4.conf.default.rp_filter = 0
      net.ipv4.conf.default.secure_redirects = 0
      net.ipv4.conf.default.send_redirects = 0
      net.ipv4.icmp_echo_ignore_broadcasts = 1
      net.ipv4.icmp_ignore_bogus_error_responses = 1
      net.ipv4.ip_forward = 1
      net.ipv4.tcp_syncookies = 1

      ## IPV6 Networking
      net.ipv6.conf.all.accept_ra = 0
      net.ipv6.conf.all.accept_redirects = 0
      net.ipv6.conf.all.accept_source_route = 0
      net.ipv6.conf.all.forwarding = 0
      net.ipv6.conf.default.accept_ra = 0
      net.ipv6.conf.default.accept_redirects = 0
      net.ipv6.conf.default.accept_source_route = 0

      ## IPV6 Disabled
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1

- name: Ensure mounting of cramfs filesystems is disabled
  become: yes
  copy:
    dest: "/etc/modprobe.d/cramfs.conf"
    content: |
      install cramfs /bin/true

- name: Ensure mounting of dccp filesystems is disabled
  become: yes
  copy:
    dest: "/etc/modprobe.d/dccp.conf"
    content: |
      install dccp /bin/true

- name: Ensure mounting of freevxfs filesystems is disabled
  become: yes
  copy:
    dest: "/etc/modprobe.d/freevxfs.conf"
    content: |
      install freevxfs /bin/true

- name: Ensure mounting of hfs filesystems is disabled
  become: yes
  copy:
    dest: "/etc/modprobe.d/hfs.conf"
    content: |
      install hfs /bin/true

- name: Ensure mounting of hfsplus filesystems is disabled
  become: yes
  copy:
    dest: "/etc/modprobe.d/hfsplus.conf"
    content: |
      install hfsplus /bin/true

- name: Ensure mounting of jffs2 filesystems is disabled
  become: yes
  copy:
    dest: "/etc/modprobe.d/jffs2.conf"
    content: |
      install jffs2 /bin/true

- name: Ensure mounting of rds filesystems is disabled
  become: yes
  copy:
    dest: "/etc/modprobe.d/rds.conf"
    content: |
      install rds /bin/true

- name: Ensure mounting of sctp filesystems is disabled
  become: yes
  copy:
    dest: "/etc/modprobe.d/sctp.conf"
    content: |
      install sctp /bin/true

- name: Ensure mounting of squashfs filesystems is disabled
  become: yes
  copy:
    dest: "/etc/modprobe.d/squashfs.conf"
    content: |
      install squashfs /bin/true

- name: Ensure mounting of tipc filesystems is disabled
  become: yes
  copy:
    dest: "/etc/modprobe.d/tipc.conf"
    content: |
      install tipc /bin/true

- name: Ensure mounting of udf filesystems is disabled
  become: yes
  copy:
    dest: "/etc/modprobe.d/udf.conf"
    content: |
      install udf /bin/true

- name: Disable IPV6
  become: yes
  copy:
    dest: "/etc/modprobe.d/ipv6.conf"
    content: |
      blacklist ipv6

- name: Disable Bluetooth
  become: yes
  copy:
    dest: "/etc/modprobe.d/disable_bluetooth.conf"
    content: |
      blacklist hci_uart
      blacklist hidp
      blacklist rfcomm
      blacklist btbcm
      blacklist bnep
      blacklist bluetooth

- name: Disable Wi-Fi Power Saving
  become: yes
  copy:
    dest: "/etc/modprobe.d/disable_wifi_powersaving.conf"
    content: |
      options 8192cu rtw_power_mgnt=0
      options 8188eu rtw_power_mgnt=0
      options 8189es rtw_power_mgnt=0
      options 8723bs rtw_power_mgnt=0
      options wlan_8192eu rtw_power_mgnt=0

- name: Reload Sysctl Changes
  become: yes
  command: sysctl -p 
  register: sysctl_status
  changed_when: false
  tags: sysctlreload